apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-kernelnet1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_kernel1
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-kernelnet1",
  "spoofchk": "off",
  "type": "sriov",
  "vlan": 1000,
  "ipam": {
    "type": "whereabouts",
    "range": "10.128.144.0/23",
    "range_start": "10.128.145.180",
    "range_end": "10.128.145.185",
    "gateway": "10.128.144.1"
  }  
}'

