apiVersion: v1
kind: Pod
metadata:
  name: testpod-kernelsingle4
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
        "name": "sriov-kernelnet1"
      }
    ]'
spec:
  containers:
  - name: testpod3
    image: rparikh/dpdk-app-centos
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/podnetinfo
      name: podnetinfo
      readOnly: false
    resources:
      requests:
        memory: 1Gi
        intel.com/intel_sriov_kernel1: 1
        #cpu: "4"
      limits:
        #cpu: "4"
        intel.com/intel_sriov_kernel1: 1
    # Uncomment to control which DPDK App is running in container.
    # If not provided, l3fwd is default.
    #   Options: l2fwd l3fwd testpmd
    #env:
    #- name: DPDK_SAMPLE_APP
    #  value: "l2fwd"
    #
    # Uncomment to debug DPDK App or to run manually to change
    # DPDK command line options.
    command: ["sleep", "infinity"]
  volumes:
  - name: podnetinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
