# permissions for end users to view hostnetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostnetwork-viewer-role
rules:
- apiGroups:
  - plumber.k8s.pf9.io
  resources:
  - hostnetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - plumber.k8s.pf9.io
  resources:
  - hostnetworks/status
  verbs:
  - get
