---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-plumber-k8s-pf9-io-v1-networkplugins
  failurePolicy: Fail
  name: vnetworkplugins.kb.io
  rules:
  - apiGroups:
    - plumber.k8s.pf9.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkplugins
  sideEffects: None
