//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 Platorm9.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	netx "net"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPConfig) DeepCopyInto(out *BGPConfig) {
	*out = *in
	if in.RemotePeers != nil {
		in, out := &in.RemotePeers, &out.RemotePeers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemoteASN != nil {
		in, out := &in.RemoteASN, &out.RemoteASN
		*out = new(int)
		**out = **in
	}
	if in.MyASN != nil {
		in, out := &in.MyASN, &out.MyASN
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPConfig.
func (in *BGPConfig) DeepCopy() *BGPConfig {
	if in == nil {
		return nil
	}
	out := new(BGPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkWizard) DeepCopyInto(out *NetworkWizard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkWizard.
func (in *NetworkWizard) DeepCopy() *NetworkWizard {
	if in == nil {
		return nil
	}
	out := new(NetworkWizard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkWizard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkWizardList) DeepCopyInto(out *NetworkWizardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkWizard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkWizardList.
func (in *NetworkWizardList) DeepCopy() *NetworkWizardList {
	if in == nil {
		return nil
	}
	out := new(NetworkWizardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkWizardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkWizardSpec) DeepCopyInto(out *NetworkWizardSpec) {
	*out = *in
	if in.RangeStart != nil {
		in, out := &in.RangeStart, &out.RangeStart
		*out = make(netx.IP, len(*in))
		copy(*out, *in)
	}
	if in.RangeEnd != nil {
		in, out := &in.RangeEnd, &out.RangeEnd
		*out = make(netx.IP, len(*in))
		copy(*out, *in)
	}
	if in.BGPConfig != nil {
		in, out := &in.BGPConfig, &out.BGPConfig
		*out = new(BGPConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkWizardSpec.
func (in *NetworkWizardSpec) DeepCopy() *NetworkWizardSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkWizardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkWizardStatus) DeepCopyInto(out *NetworkWizardStatus) {
	*out = *in
	if in.IPAllocations != nil {
		in, out := &in.IPAllocations, &out.IPAllocations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkWizardStatus.
func (in *NetworkWizardStatus) DeepCopy() *NetworkWizardStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkWizardStatus)
	in.DeepCopyInto(out)
	return out
}
