# permissions for end users to edit networkplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: networkplugins-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: luigi
    app.kubernetes.io/part-of: luigi
    app.kubernetes.io/managed-by: kustomize
  name: networkplugins-editor-role
rules:
- apiGroups:
  - plumber.k8s.pf9.io
  resources:
  - networkplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plumber.k8s.pf9.io
  resources:
  - networkplugins/status
  verbs:
  - get
