---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - plumber.k8s.pf9.io
  resources:
  - networkwizards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plumber.k8s.pf9.io
  resources:
  - networkwizards/finalizers
  verbs:
  - update
- apiGroups:
  - plumber.k8s.pf9.io
  resources:
  - networkwizards/status
  verbs:
  - get
  - patch
  - update
