apiVersion: plumber.k8s.pf9.io/v1
kind: NetworkPlugins
metadata:
  labels:
    app.kubernetes.io/name: networkplugins
    app.kubernetes.io/instance: networkplugins-sample
    app.kubernetes.io/part-of: luigi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: luigi
  name: networkplugins-sample
spec:
  # TODO(user): Add fields here
