apiVersion: plumber.k8s.pf9.io/v1
kind: NetworkPlugins
metadata:
  name: networkplugins-sample11
spec:
  # Add fields here
  #privateRegistryBase: "localhost:5100"
  plugins:
    hostPlumber: {}
    nodeFeatureDiscovery: {}
    multus: {}
    whereabouts:
      ipReconcilerSchedule: "*/100 * * * *"
      #ipReconcilerNodeSelector:
         #foo: bar
    # SRIOV actually consists of two plugins - the CNI, and the device-plugin
    # VFs need to be created before deploying SRIOV - manually or use hostplumber
    #sriov: {}
    ovs: {}
    dhcpController: {}
