# permissions for end users to view ipallocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipallocation-viewer-role
rules:
- apiGroups:
  - dhcp.plumber.k8s.pf9.io
  resources:
  - ipallocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dhcp.plumber.k8s.pf9.io
  resources:
  - ipallocations/status
  verbs:
  - get
