---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dhcp.plumber.k8s.pf9.io
  resources:
  - ipallocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dhcp.plumber.k8s.pf9.io
  resources:
  - ipallocations/finalizers
  verbs:
  - update
- apiGroups:
  - dhcp.plumber.k8s.pf9.io
  resources:
  - ipallocations/status
  verbs:
  - get
  - patch
  - update
