name: Unit Tests and Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    environment: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          go-version: 1.17
          check-latest: true
          cache: true
      - name: Print the version of golang
        run: go version
#      - name: Run golangci-lint
#        uses: golangci/golangci-lint-action@v3.4.0
#        with:
#          skip-pkg-cache: true
#          args: --timeout=5m
  build_and_unit_test:
    environment: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          go-version: 1.17
          check-latest: true
          cache: true
      - name: Print the version of golang
        run: go version
      - name: Run unit tests with code coverage
        run: make test
      - name: Build
        run: make build
      - name: Go Coverage
        uses: gwatts/go-coverage-action@v1.3.0
      - name: Generate coverage tree map
        run: |
         go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest; \
         go run github.com/nikolaydubina/go-cover-treemap@latest \
          -coverprofile ${{ steps.coverage.outputs.gocov-agg-pathname }} \
          -only-folders=true >/tmp/treemap.svg        

