name: Caller Workflow

on:
  push:
    branches:
      - private/shweta/ovs-multi-arch
  pull_request:
    branches:
      - private/shweta/ovs-multi-arch
jobs:
  call-callee:
    runs-on: ubuntu-latest
    steps:
      - name: Call Callee Workflow
        uses: ./.github/workflows/ovs-multiarch-build-and-push.yml
        with:
          image-name: openvswitch
          tag: testovs
