name: Caller Workflow

on:
  push:
    branches:
      - private/shweta/ovs-multi-arch
  pull_request:
    branches:
      - private/shweta/ovs-multi-arch
jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Docker Image Build
        uses: actions/workflow-dispatch@v2
        with:
          workflow: ovs-multiarch-build-and-push.yml
          inputs:
            image-name: openvswitch
            tag: testovs
